test

diff --git a/.github/workflows/build-run-app.yml b/.github/workflows/build-run-app.yml
--- a/.github/workflows/build-run-app.yml
+++ b/.github/workflows/build-run-app.yml
@@ -48,7 +48,7 @@ jobs:
         run: |
           echo "APP_UPPER=$(echo ${{ inputs.app-name }} | sed 's/[a-z]/\U&/g')" >> $GITHUB_ENV
           echo "APP_LOWER=$(echo ${{ inputs.app-name }} | sed 's/[A-Z]/\L&/g')" >> $GITHUB_ENV
-          echo "APP_PROPER=$(echo ${{ inputs.app-name }} | sed -e 's/\b\(.\)/\u\1/g' -e 's/\b\(.\)/\u\1/g')" >> $GITHUB_ENV
+          echo "IS_SAMPLE_OR_LAB=$(echo ${{ inputs.app-name }} | grep -iqE 'sample|lab' && echo true || echo false)" >> $GITHUB_ENV
 
       - name: Set up start string for verification
         run: |
@@ -76,13 +76,13 @@ jobs:
 
       - name: Add To Build
         run: |
-          if [[ "$APP_LOWER" != "sample_app" ]]; then
+          if [[ "$IS_SAMPLE_OR_LAB" == "false" ]]; then
             sed -i "/list(APPEND MISSION_GLOBAL_APPLIST/a list(APPEND MISSION_GLOBAL_APPLIST $APP_LOWER)" sample_defs/targets.cmake
           fi
 
       - name: Add To Startup
         run: |
-          if [[ "$APP_LOWER" != "sample_app" ]]; then
+          if [[ "$IS_SAMPLE_OR_LAB" == "false" ]]; then
             sed -i "1i CFE_APP, $APP_LOWER, ${APP_UPPER}_AppMain, $APP_UPPER, 80, 16384, 0x0, 0;" sample_defs/cpu1_cfe_es_startup.scr
             cat sample_defs/cpu1_cfe_es_startup.scr
           fi
@@ -105,22 +105,12 @@ jobs:
 
       - name: Confirm startup string
         run: |
-          if [[ "$APP_LOWER" == "sample_app" ]]; then
-            if [[ -z $(grep "$APP_PROPER" cFS_startup_cpu1.txt) ]]; then
-              echo "Startup verification string not found in log: $APP_PROPER"
-              echo ""
-              echo "Possible related event messages:"
-              grep "/$APP_PROPER " cFS_startup_cpu1.txt
-              exit -1
-            fi
-          else
-            if [[ -z $(grep "$START_STRING" cFS_startup_cpu1.txt) ]]; then
-              echo "Startup verification string not found in log: $START_STRING"
-              echo ""
-              echo "Possible related event messages:"
-              grep "/$APP_UPPER " cFS_startup_cpu1.txt
-              exit -1
-            fi
+          if [[ -z $(grep "$START_STRING" cFS_startup_cpu1.txt) ]]; then
+            echo "Startup verification string not found in log: $START_STRING"
+            echo ""
+            echo "Possible related event messages:"
+            grep "/$APP_UPPER " cFS_startup_cpu1.txt
+            exit -1
           fi
 
       - name: Check for cFS Warnings
